### ISSUE TITLE
[Feature Request] More control over ads and how they appear

### ISSUE THREAD

**Issue by lemonnuggets** [gladly-team/tab#869] opened 2021-02-05 15:01 UTC
It would be very helpful if you could let the user decide where the ads show up on the screen. It is really strange and offputting to see that there is one ad at the bottom and then there are two on the right. The ad at the bottom isn't even centered. I'm not sure if this is intentional, but I don't see why it should be this way. Maybe there could be some presets that they could choose from like ads on the side or ads at the top and bottom. Or let the user freely place the ads anywhere on the screen as they see fit. I don't know if the second one is possible but just a suggestion.
Also, another kinda related thing that would greatly improve user experience is maybe letting them decide how many ads they see, with a minimum of one or two ads but the option for more? A good example of a site that does this is monkeytype.com.

**Comment by kmjennison** [comment] 2021-02-05 16:16
Closing as a duplicate of #421.

@lemonnuggets Thanks for sharing! We're definitely open to this customization. Just curious, how would you want to arrange the ads if there were only two ads on the page?

**Closed by kmjennison** 2021-02-05 16:16 UTC
Labels: duplicate

**Comment by lemonnuggets** [comment] 2021-02-05 16:29
Okay sorry but I didn't see that previous issue. The way I was thinking of it was like there could be four boxes, one each at the bottom, top, left, and right edge of the window. And in the settings you can choose which all boxes you want ads to be displayed in. 
But yeah this could pose potential problems with the existing layout of the window. So I guess I'd even just prefer to have an option to choose between top and bottom banner ads and left and right banner ads.

**Comment by kmjennison** [comment] 2021-02-05 16:31
Got it, thanks! This is on our radar.
